### ISSUE TITLE
Load More button acts unpredictable

### ISSUE THREAD

**Issue by norrec99** [near-in-minutes/frontend#60]
When you hit `load more` a couple of times it should look like this at the end;

- ![load_more_bug2](https://user-images.githubusercontent.com/45902312/124936514-4e6f9980-e00f-11eb-9e9b-31d2d02bf56e.PNG)

But if you keep hitting the button, it looks like this;

- ![load_more_bug4](https://user-images.githubusercontent.com/45902312/124936693-6f37ef00-e00f-11eb-8acb-410b085611dc.PNG)

Need to fix duplicate videos and disable the `load more` button when there are no more videos to show

**Comment by humanman** [comment]
Could be related to this:
`    function renderContentId(v) {
      return v.content ? v.content[0] : '';
    }`
default to first item in list, which would explain the one item duplicating itself.
